### ISSUE TITLE
NullPointerException when importing in docker

### ISSUE THREAD

**Issue by jennyxu6** [sebischair/akre-server#13]
This issue appears when importing a project in docker.

Step 1 finishes successfully. Step 2 throws the following exception:

>docclassification_1
Internal server error, for (POST) [/pipeline/predict] ->
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
...
Caused by: java.lang.NullPointerException: null
at util.pipeline.ExamplePredictionPipeline.loadModel(ExamplePredictionPipeline.java:21)
at util.prediction.PredictionPipeline.execute(PredictionPipeline.java:26)
at controllers.PipelineController.predict(PipelineController.java:102)
...
akre_1
[error] application - Unable to label an issue

Not sure whether this is related to the refused connection at SpacyHost:
>[error] application - [http://131.159.30.9:5000/api] server error: java.net.ConnectException: Connection refused: /131.159.30.9:5000

**Comment by manoj5864** [comment]
It's for sure not related to SpacyHost..

The problem is that Play cannot find myresources folder..

**Comment by jennyxu6** [comment]
This is fixed in commit 77bf59b13b3277f8318566085eb432bf932a634.
